### ISSUE TITLE
secure-delete on ReactOS

### ISSUE THREAD

**Issue by UserX00** [gordonrs/thc-secure-delete#2]
Hi Mr. Gordon Speirs, I have a dude: 
are you planning to port 'secure-delete' utilities to be compatible with ReactOS?

'ReactOS' is an Open Source Windows XP-like OS, still in alpha stage development. Cause Microsoft Windows is closed source.

**Comment by gordrs** [comment]
Nah I’m not planning on doing anything with this other than ensuring that it still builds. I don’t even think the Linux kernel module part for this has worked in years and I have zero interest (at the moment) in maintaining that part. Also zero plans on supporting ReactOS. There would be way too many incompatibilities and a total change to the build system I’d imagine.
